Voyageur/Voyageur/Areas/Admin/Controllers/AdminHomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Voyageur.Models;

namespace Voyageur.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminHomeController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Admin/Home
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }
        public ActionResult RolAta()
        {
            return View();

        }

        [HttpPost]
        public async Task<ActionResult> RolAta(String id)
        {
            var user = await UserManager.FindByIdAsync(id);
            var userStore = new UserStore<ApplicationUser>(db);
            var userManager = new UserManager<ApplicationUser>(userStore);
            if (user.Email == "mustafa.glr97@gmail.com")
            {
                userManager.AddToRole(user.Id, "Admin");
            }
            else
            {
                userManager.AddToRole(user.Id, "Uye");
            }
            return RedirectToAction("Index");

        }



    }

}

Voyageur/Voyageur/Areas/Admin/Views/AdminHome/Index.cshtml
@model IEnumerable<Voyageur.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <table class="table">
        <tr>
            <th>
                UserName
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("Rol ata", "RolAta", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

Voyageur/Voyageur/Areas/Admin/Views/AdminHome/RolAta.cshtml
@model Voyageur.Models.RegisterViewModel

@{
    ViewBag.Title = "RolAta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RolAta</h2>

<div class="form-horizontal">
    <hr />


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @Value = "~/images/" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
           @Html.ActionLink("Rol Ata", "RolAta", "AdminHome", new { id = Model.Email }, null)
        </div>
    </div>
</div>