Voyageur/Voyageur/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Voyageur.Context;
using Voyageur.Models;

namespace Voyageur.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private UyeContext db = new UyeContext();

        // GET: Chat
        public ActionResult Index()
        {
            ViewBag.UserName = User.Identity.Name;
            return View();
        }


   
    }
}

Voyageur/Voyageur/Controllers/EditModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Voyageur.Context;
using Voyageur.Models;

namespace Voyageur.Controllers
{
    [Authorize]
    public class EditModelsController : Controller
    {
        private UyeContext db = new UyeContext();

        // GET: EditModels
        public ActionResult Index()
        {
            return View(db.Edit.Where(x => x.UserName == User.Identity.Name).ToList());

        }

        // GET: EditModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EditModels editModels = db.Edit.Find(id);
            if (editModels == null)
            {
                return HttpNotFound();
            }
            return View(editModels);
        }

        // GET: EditModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EditModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Address,Number,BirthDay,UserName")] EditModels editModels)
        {

            if (ModelState.IsValid)
            {
                db.Edit.Add(editModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(editModels);
        }

        // GET: EditModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EditModels editModels = db.Edit.Find(id);
            if (editModels == null)
            {
                return HttpNotFound();
            }
            return View(editModels);
        }

        // POST: EditModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address,Number,BirthDay,UserName")] EditModels editModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(editModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(editModels);
        }

        // GET: EditModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EditModels editModels = db.Edit.Find(id);
            if (editModels == null)
            {
                return HttpNotFound();
            }
            return View(editModels);
        }

        // POST: EditModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EditModels editModels = db.Edit.Find(id);
            db.Edit.Remove(editModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

      
    }
}

Voyageur/Voyageur/Controllers/ShareModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Voyageur.Context;
using Voyageur.Models;

namespace Voyageur.Controllers
{
    [Authorize]

    public class ShareModelsController : Controller
    {
        private UyeContext db = new UyeContext();

        [AllowAnonymous]
        // GET: ShareModels
        public ActionResult Index()
        {
            return View(db.Share.ToList());
        }


        // GET: ShareModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShareModels shareModels = db.Share.Find(id);
            if (shareModels == null)
            {
                return HttpNotFound();
            }
            return View(shareModels);
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: ShareModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Image,Name,Address,Comment,Point,Kategori")] ShareModels shareModels)
        {
            if (ModelState.IsValid)
            {
                db.Share.Add(shareModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shareModels);
        }

        // GET: ShareModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShareModels shareModels = db.Share.Find(id);
            if (shareModels == null)
            {
                return HttpNotFound();
            }
            return View(shareModels);
        }

        // POST: ShareModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Image,Name,Address,Comment,Point,Kategori")] ShareModels shareModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shareModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shareModels);
        }

        // GET: ShareModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShareModels shareModels = db.Share.Find(id);
            if (shareModels == null)
            {
                return HttpNotFound();
            }
            return View(shareModels);
        }

        // POST: ShareModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ShareModels shareModels = db.Share.Find(id);
            db.Share.Remove(shareModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Voyageur/Voyageur/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Voyageur</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <img id="logo" src="~/images/LogoMakr.png" width="100%">
    <nav class="navbar navbar-inverse navs " >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VOYAGEUR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand octinbaslik" })
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-th-list"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink(Resources.Home.Chat, "Index", "Chat")</li>
                            <li>@Html.ActionLink(Resources.Home.Paylas, "Create", "ShareModels")</li>
                            <li>@Html.ActionLink(Resources.Home.Favori_Mekanlar, "Index", "ShareModels")</li>
                        </ul>
                    </li>
                </ul>
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <ul class="navbar-form navbar-right">
                            <li>
                            @ViewBag.User
                                @Html.ActionLink(Resources.Home.Hello+" " +User.Identity.Name, "Index", "EditModels", routeValues: null, htmlAttributes: new { title = "Profil" })
                            
                            <button type="button" id="loginLink" class="btn btn-danger" onclick="javascript:document.getElementById('logoutForm').submit()">@Resources.Home.Cıkıs<span class="glyphicon glyphicon-off" /></button>
                                <var class="dropdown">
                                    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                                        @Resources.Home.Dil
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li>@Html.ActionLink("TR", "Change", "Home", new { LanguageAbbrevation = "tr" }, null)</li>
                                        <li>@Html.ActionLink("EN", "Change", "Home", new { LanguageAbbrevation = "en" }, null)</li>
                                    </ul>
                                </var></li>
                        </ul>
                  
                    }

                }
                else
                {
                    using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                <ul class="navbar-form navbar-right">
                    <li><button type="button" id="registerLink" class="btn btn-success" onclick="location.href='@Url.Action("Login", "Account")'">@Resources.Home.Giris <span class="glyphicon glyphicon-log-in" /></button>
                    <button type="button" id="loginLink" class="btn btn-danger" onclick="location.href='@Url.Action("Register", "Account")'">@Resources.Home.Kaydol <span class="glyphicon glyphicon-floppy-save" /></button>                       
                        <var class="dropdown">
                            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                                @Resources.Home.Dil
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li>@Html.ActionLink("TR", "Change", "Home", new { LanguageAbbrevation = "tr" }, null)</li>
                                <li>@Html.ActionLink("EN", "Change", "Home", new { LanguageAbbrevation = "en" }, null)</li>
                            </ul>
                        </var>
                    </li>

                </ul>
                    }
                }

            </div>
        </div>
    </nav>
    <br />
    <br />
    <div class="container">
        @RenderBody()

    </div>
    <br />
    <br />

    <div class="container-fluid footer">
        <br />

        <div class=" container ">
            <p> @DateTime.Now.Year - © Copyright 2016  Mustafa Güler</p>

        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>